version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  versioning-strategy: increase
  ignore:
  - dependency-name: react-router
    versions:
    - ">= 5.1.a"
    - "< 5.2"
  - dependency-name: react-router
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: react-router-dom
    versions:
    - "> 4.3.1"
