language: node_js
node_js:
  - "10"
branches:
  only:
  - master
script:
  - npm run build
  - npm run test
deploy:
  - provider: pages
    cleanup: false
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: master
    on:
      branch: master
