name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install
      run: npm install --legacy-peer-deps
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Commit
      env:
        PUBLISH_GLOB: lib
        PUBLISH_USER: github-actions
        PUBLISH_EMAIL: actions@users.noreply.github.com
      run: |
        git config user.name ${PUBLISH_USER}
        git config user.email ${PUBLISH_EMAIL}
        git add ${PUBLISH_GLOB}
        git status # useful for debugging
        git commit -m "chore: deploy website [skip ci]" || exit 0
    - name: Deploy
      if: github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: ${{ github.ref }}
        force: true
