name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      env:
        BRANCH_NAME: master
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_GLOB: lib
        PUBLISH_USER: CI Bot
        PUBLISH_EMAIL: actions@users.noreply.github.com
      run: |
        git config http.sslVerify false
        git config user.name ${PUBLISH_USER}
        git config user.email ${PUBLISH_EMAIL}
        git remote add publisher "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git show-ref # useful for debugging
        git branch --verbose
        git add ${PUBLISH_GLOB}
        git commit -m "chore: deploy website [skip ci]" || exit 0
        git pull --rebase publisher ${BRANCH_NAME}
        git push publisher ${BRANCH_NAME}
