name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 8
    - name: Build
      run: pnpm run build
    - name: Test
      run: pnpm run test
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      run: |
        echo 'serverless api deployment'
